apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sznbi7lnd-python 
  janus-idp.io/tekton: sznbi7lnd-python
  backstage.io/kubernetes-id: sznbi7lnd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sznbi7lnd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml